### ISSUE TITLE
Play Store のレビューを取得できない

### ISSUE THREAD

**Issue by hmiyado** [seriwb/reviewet#14]
いつのころからか、 play store の HTML に人間が読むことのできるクラス名やID名が入らなくなったようです。
結果、レビューを取得できなくなりました。

**Comment by seriwb** [comment]
報告ありがとうございます。
Headless Chromeを使って対応できないか試してみます。

**Comment by seriwb** [comment]
version 2で対応させれそうなので、そちらで対応します #25

**Comment by seriwb** [comment]
@hmiyado 
おまたせしました。☆の取得以外はとりあえずできるように修正しました。
